# political-scorecard-backend/src/main/resources/application.yml
spring:
  application:
    name: political-scorecard-backend
  profiles: # Note: Can activate multiple profiles by separating them with a comma, ex: "local,test".
    active: dev # Default profile set directly in config (previously from SPRING_PROFILES_ACTIVE env var)